trigger:
  - master

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: BuildJob
    displayName: 'Build Job 1'
    pool:
      vmImage: 'ubuntu-latest'
    continueOnError: true
    steps:
    - script: echo This is the Build stage!

- stage: Deploy
  dependsOn: Build
  displayName: 'Deploy Stage'
  jobs:
  - deployment: deploymentjob
    displayName: 'deployment job'
    pool:
      vmImage: 'ubuntu-latest'
    continueOnError: true
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo This is the Deploy stage!

- stage: Final
  dependsOn: Deploy
  displayName: 'Final'
  jobs:
  - job: FinalJob
    displayName: 'Final Job 1'
    pool:
      vmImage: 'ubuntu-latest'
    continueOnError: true
    steps:
    - script: echo This is the Final stage!